# Generated by Django 2.2.2 on 2019-06-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoice", "0004_returned_client")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(verbose_name="product_price"),
        )
    ]
